trigger:
  batch: true
  branches:
    include:
    - main
pr:
  - main
variables:
  MajorVersion : 0
  MinorVersion : 0
  PatchVersion : $[counter(format('nexus-extension-{0}.{1}.{2}',variables['Build.SourceBranchName'],variables['MajorVersion'],variables['MinorVersion']), 90)]
  isPR : $[startsWith(variables['Build.SourceBranch'],'refs/pull/')] 
  isMain : $[startsWith(variables['Build.SourceBranch'],'refs/heads/main')] 
stages:
  - stage : build_package
    displayName: Build & Package Extension
    jobs:
      - job : build_package
        displayName: Build & Package Extension
        pool:
          vmImage: 'windows-latest'
        steps:
        - checkout: self
          persistCredentials: true
          clean: true
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
        - script: npm install -g tfx-cli
          displayName: 'Install Node CLI for Azure DevOps'
        - script: npm install
          displayName: 'Install Dependencies'
        - script: npm run lint
          displayName: 'Run ESLint'
          condition: eq(variables.isPR, true)
        - script: |
            npm run build
          condition: eq(variables.isPR, true)
          displayName: 'Build Extension'
        - script: |
            npm run package -- --override {\"version\": \"$(MajorVersion).$(MinorVersion).$(PatchVersion)\"}
          displayName: 'Build & Package Extension'
          condition: eq(variables.isMain, true)
        - task: PowerShell@2
          displayName: 'Tag Git Commit'
          condition: eq(variables.isMain, true)
          inputs:
            targetType: 'inline'
            script: |
              git tag "v$(MajorVersion).$(MinorVersion).$(PatchVersion)"
        - task: PowerShell@2
          displayName: 'Push Git Tags'
          condition: eq(variables.isMain, true)
          inputs:
            targetType: 'inline'
            script: |
              git push --tags
        - task: GitHubRelease@1
          displayName: 'Publish Extension as Release'
          condition: eq(variables.isMain, true)
          inputs:
            gitHubConnection: 'github.com_keyoke'
            repositoryName: '$(Build.Repository.Name)'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'gitTag'
            tagPattern: 'v$(MajorVersion).$(MinorVersion).$(PatchVersion)'
            assets: '$(System.DefaultWorkingDirectory)\packages\*.vsix'
            changeLogCompareToRelease: 'lastFullRelease'
            changeLogType: 'commitBased'
  